name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mamba=1.0
  - conda=22.9.0
  - python=3.10
  - scanpy=1.9.1
  - nextflow=22.10.0
  - fastqc=0.11.9
  - trimmomatic=0.39
  - bowtie2=2.4.5
  - picard=2.27.4
  - star=2.7.10b
  - macs2=2.2.7.1
  - r-biocmanager=1.30.19
  - r-devtools=2.4.5
  - r-dplyr=1.0.10
  - r-ggrepel=0.9.1
prefix: /opt/conda
